### ISSUE TITLE
Conservation brush for Priorparken workstations

### ISSUE THREAD

**Issue by RebekkaML** [NHMDenmark/Herbarium-Sheets-workstation#158]
Since some of the Herbarium specimens cause a lot of dust and plants crumbs, @Gomismis suggested getting a broad conservation brush to clean the workstations from time to time. 

She suggested something like this: https://www.preservationequipment.com/Catalogue/Equipment-Tools/Brushes/Conservation-Brushes/Wide-handle-conservation-brushes

Options 1, 2 and 3 from that link all seem to fit our needs. 

@Sara suggested choosing the horse hair option: "Goat hair is quite a lot softer than horse hair and probably wouldn't scratch the imaging plate, but the bristles would probably break faster.
Since the plate is already scratched from the herbarium sheets and plant debris, I would suggest horse hair as the sturdier option".
She will find a fitting brush from a danish supplier.

**Comment by nms419** [comment]
The closest match from a danish supplier would be a wallpaper brush. I have opted for brushes at least 35 cm long, because the herbarium imaging stations are so large and have found these two options where it is possible to pay with EAN:

https://picment.dk/tapetborste 
![image](https://github.com/user-attachments/assets/980002e9-c763-48d0-9eb3-b6a7a39a59ad)


https://decofarver.dk/shop/spekter-tapetboerste-35-4888p.html
![image](https://github.com/user-attachments/assets/0095f30b-cbce-45be-9058-2a0c5c2e6b9d)

I think the first option is the easiest to incorporate into the workflow because of the handle. If we add a hook to the imaging enclosure it would be easy to store and grab while digitizing.

**Comment by RebekkaML** [comment]
After talking to Matilde again, she thought the options Sara suggested are a bit large, but there were not a lot of smaller ones that we could find. 
Matilde then suggested this brush, which is 26 x 7 x 1 cm and should be a good medium size:
https://blindesarbejde.dk/vare/bordboerste-med-gedehaar/
![blindesarbejde_brush](https://github.com/user-attachments/assets/d8f06714-4638-48d2-9fc1-51dbe3c026e6)

**Comment by RebekkaML** [comment]
I ordered 2 of the brushes (from bllindesarbejde) suggested by Matilde today.

**Comment by RebekkaML** [comment]
The brushes arrived and I placed them at the workstations yesterday (18.12.2024).
