### ISSUE TITLE
Work out AU workflow

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#20]

**Comment by chelseagraham** [comment]
Draft workflow doc at: N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and workstations/HerbariumImaging/HerbariumAAU_DigiTrainingDoc_20230515_cg.doc


Directory where images are currently being stored is E:/DaSSCo_Digitization



Workflow Deviations:


**Folder to be imaged before all sheets within (= ### triangle shape indicator magnet?)**


a.	If you encounter damaged or loose specimens
i.	exercise caution and handle very carefully
ii.	image as usual

b.	If you encounter a specimen with loose fragments
i.	place the fragments into the envelope on the sheet
ii.	if the sheet does not have an envelope, take care to maintain association of the fragments with the specimen

c.	If you encounter active (living) pest damage
i.	alert Collections Managers immediately

d.	If you encounter a multi-specimen / multi-collection sheet containing multiple barcoded specimens
i.	place a ### square shape indicator magnet at the end of the black institutional scale bar 
ii.	image as usual
iii.	remember to remove the shape indicator from the scale bar after imaging

e.	If you encounter a multi-sheet specimen with a label only on the first sheet, or with duplicated subsequent labels and with each sheet containing their own barcode
i.	image as usual
 
f.	If you encounter a sheet with multiple foldouts in layers containing multiple barcoded specimens
i.	take care to arrange the sheet in the field of view
ii.	image as usual

g.	If you encounter an irregular sized sheet
i.	arrange the sheet to line up with the angle 
ii.	image as usual

**h.	If you encounter a sheet that only contains specimens within envelopes
i.	open the envelopes and arrange the specimens
ii.	image as usual**

**i.	If you encounter a sheet that is folded in half and contains a label on the front and the specimen(s) without context inside 
or a folded sheet with a specimen on either side but a label only corresponding to one
i.	place a ### circle shape indicator magnet at the end of the black institutional scale bar 
ii.	image the outside of the folded sheet
iii.	open the sheet and line it up with the angle (the specimen may be upside down)
iv.	image the specimen
v.	remember to remove the shape indicator from the scale bar after imaging**

**j.	If you encounter a specimen with a label or information on the back of the sheet
i.	skip, do not image
ii.	set aside for Collections Manager to image in order to capture (in order to capture information on back and maintain association with specimen)
iii.	Collections Manager: use a ### circle shape indicator when imaging**

**k.	If you encounter a specimen with no label or information
i.	place a ### circle shape indicator magnet at the end of the black institutional scale bar (to relate it to the last sheet with a label)
ii.	image as usual
iii.	remember to remove the shape indicator from the scale bar after imaging**

**l.	If you encounter a type specimen in a red folder at Aarhus Herbarium
i.	image the folder and specimen as usual
ii.	skip, do not image accompanying reference materials**
 
**m.	If you encounter a type specimen in a general folder
i.	image as usual
ii.	set aside for Collections Managers**

n.	If you encounter a multi-collection sheet with different species present, or a sheet that is in the wrong folder
i.	set the sheet aside for a Collections Manager to remount or put away in the correct place


Sheets do not need to be reordered when transferred back into folder.
Folders may need to be reordered if they are out of alphabetical order. If all have same Species name, this is not necessary. 


Run Axel's GUI before Thomas' GUI???

**Comment by chelseagraham** [comment]
Workflow on N:/SCI-SNM-DigitalCollections/DaSSCo/Workflows and Workstations

**Comment by PipBrewer** [comment]
Closing issue as it is unclear whether AU will be using this workflow now. We will wait to hear from them.
