### ISSUE TITLE
Issues with camera

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#3]
Reported by CL and JW to PB today during meeting. 

Issue 1: Justin has managed to reproduce the camera drifting error that they had at Aarhus. They have found a significant drift at Priorparken and are testing to figure out why. It happened when the camera was left over lunch break. However, Birgitte thinks it has happened to her during an imaging session. 

Issue 2: Also there is a bobbing of the live view and they tested it by changing exposure - the actual images do bob back and forth in and out of focus. Can be solved by decreasing exposure time (1/60th of second, ISO200). Christian has a theory that the building is shaking due to air con unit. Birgitte is testing it at Aarhus.

**Comment by PipBrewer** [comment]
Emailed Roberta to see if has any ideas on 14/12/2022
Mentioned in Digital Collections slack on 14/12/2022
Emailed Laura Green (Kew) on 14/12/2022

**Comment by chelseagraham** [comment]
Went out to Priorparken to assess issues on 5 Jan 2023

**Drift experienced within a session:**
Could not reproduce the drifting error over the time period of 30 minutes. 
Spoke with Justin and it seemed he was not able to reproduce the focus drift issue experienced in Aarhus within a session.
_Should be standard practice to assess focus every few hundred sheets_

**Drift experienced after a break:**
_Should be standard practice to re-establish focus after a break_

**Bobbing in Live View:**
Could not reproduce the bobbing issue.
Seems to be building related.

Justin has adopted the settings suggested by Laura Green (which center around continuous focus, similar to those suggested by Fuji Film technician Richard Benodck), however it seems that these are overridden by selecting Manual in Capture One. 

The settings Justin selected seemed to remedy the situation:
M
ISO 200
aperture f/ 5.6
shutter speed 1/60th second 

This does not make the most optimal use of the lens. The sweet spot for this lens would be an aperture within the range of of f/8-f/11. 

Asking Justin to test:
If shooting in AE (aperture priority exposure mode) instead of M (manual exposure mode), the AF-C (continuous focus) may stay enabled. If we adopt one of the F/ stops that yield the crispest shots, would the longer shutter speed incur blurring due to the building vibrations?

**Comment by chelseagraham** [comment]
Tested
