### ISSUE TITLE
Overhead light on base of workstation can be seen in image

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#31]
You can clearly see in image that light is shining (and reflecting) on base of workstation below sheet (see on 22/02/2023).
Can this be reduced by having the top of the workstation lower and slightly angled or sticking further out horizontally (would also provide easier access to camera and make it easier to see camera settings)
Does there need to be a lip or protrusion on top of workstation as it is
Check both - what are the pros and cons?
Is there an alternative solution

**Comment by chelseagraham** [comment]
The lamps overpower the ambient light, so the ambient light does not impact the scene.
In order to assess this, images were taken of a flat white paper (mimicing a flat fields target) and pixel values were assessed across the page. The values were found to be within the tolerance level suggested by the Rijksmuseum's Photography 2D Objects Manual - Part I
https://assets.foleon.com/eu-central-1/de-uploads-7e3kk3/109/manual-2d-2021_v6.8c8ade34970e.pdf

**Comment by PipBrewer** [comment]
@chelseagraham The issue was noted when the imaging workstation had moved to a slightly different location with the overhead lights in a different position. Without testing this in different locations, we need to be aware of this as an existing potential issue?
