### ISSUE TITLE
Red button space

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#34]
Currently the red button is large in a small area and an obstruction. 

- [x] Investigate most ergonomic placement and least obstructive.
- [x] Get a smaller doorbell sized button to test in parallel. 
- [x] Investigate also pushing copy stand further back in enclosure.

**Comment by chelseagraham** [comment]
Matilde and Serena have been encountering issues with the red button (button type #2). 
They are testing the extra one I purchased. 

They will also test a foot pedal in the context of an half day block of digitizing.

**Comment by Gomismis** [comment]
We tested the footswitch and it's a hit! Hands free photographing is the best method. ATM we have a very simple foot pedal that works as a mouse click when you hit it, meaning that the cursor needs to "hover" over the shutter button in the OneCapture program. A nice update would be to buy a programmable footswitch :)

**Comment by chelseagraham** [comment]
@Gomismis Did the second of these newer, slimmer red buttons have the same issues? Is there anything in the settings for the button that can allow us to edit the sensitivity of the button?

Please look into a programmable foot pedal

**Comment by Gomismis** [comment]
So I have found a few options for both programmable foot pedals and macro switches (programmable two-three switch keyboards). I will have Chelsea order them.

**Comment by Gomismis** [comment]
I have ordered a foot pedal and a new button for the herbarium, they should be here soon :)

**Comment by Gomismis** [comment]
I have received the button for the Herbarium and it's working just perfect! but the foot pedal is somehow returned to sender. I'm trying to get them to send it back to us ATM.

**Comment by chelseagraham** [comment]
Matilde has installed and implemented different button and pedal options at Priorparken and AAU. There are options for different preferences now that cause no interference with the workstation.

**Comment by PipBrewer** [comment]
Please can you more thoroughly document the current situation and what exactly has been tested and the reasons?

**Comment by Gomismis** [comment]
We tried out buttons and foot pedals and went with the decision to use single key keyboards and foot pedals, so people can choose for them self. 
The decision to use single key keyboards was that most of them are programmable, which we needed in order to access our live imaging photo software 'capture one'. We had many difficulties with other buttons not being able to stay connected to the software resulting in 
the button either not responding or taking multiple pictures with each press. 
We also chose to install a foot pedal for hand free imaging in order to optimize the imaging workflow. the foot pedal is also programmable to avoid the same issues mentioned above.      
foot pedal is brought on amazon:
https://www.amazon.com/iKKEGOL-Footswitch-Combination-Simulator-Transcription/dp/B0B1ZJVZ2K

Most digitizers prefer the foot pedal and we are currently looking into if it should be implemented in other workstations.
