### ISSUE TITLE
Initial stats and QA

### ISSUE THREAD

**Issue by PipBrewer** [NHMDenmark/Herbarium-Sheets-workstation#42]
Start track initial stats such as how many app records per unit time and how many images. We also need some protocols for checking data and images each week to iron out issues.

**Comment by PipBrewer** [comment]
@Gomismis Could you give us summaries at every Wednesday sprint meeting starting in July?

**Comment by Gomismis** [comment]
I could indeed :)

**Comment by chelseagraham** [comment]
Digitizers tracking stats daily

**Comment by PipBrewer** [comment]
Please document more thoroughly the stats that are being tracked.

**Comment by Gomismis** [comment]
A excel document was crafted in order to keep track of our stats while digitizing. 

Data entry points includes: 
1. Date 
2. Quarter 
3. Workstation 
4. Digitizer 
5. Start time (digitizing) 
6. End time (digitizing)
7. Total time 
8. Total number of specimens 
9. Number of people (digitizers) 
10. Set up/set down time

From these entries 'Number of specimens per person' and 'Number of specimens per hour rate' are calculated. 

Entry point no. 3 (workstations) is divided into:
1. Imaging workstation 
2. Mass digitization app
3. Tiff conversion 
4. ingestion client 
These four divisions represents the steps required to fully digitize a specimen.
